In [32]:
#import libraries

import pandas as pd
import os
from sklearn.metrics import confusion_matrix
#sklearn.metrics: Score functions, performance metrics, pairwise metrics and distance computations.
#confusion_matrix: Compute confusion matrix to evaluate the accuracy of a classification.

In [33]:
link_to_data = 'https://raw.githubusercontent.com/SIT719/2020-S2/master/data/payment_fraud.csv'
dfp = pd.read_csv(link_to_data, on_bad_lines='skip')

In [34]:
dfp

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
0,29,1,4.745402,paypal,28.204861,0
1,725,1,4.742303,storecredit,0.000000,0
2,845,1,4.921318,creditcard,0.000000,0
3,503,1,4.886641,creditcard,0.000000,0
4,2000,1,5.040929,creditcard,0.000000,0
...,...,...,...,...,...,...
39216,986,1,4.836982,creditcard,0.000000,0
39217,1647,1,4.876771,creditcard,377.930556,0
39218,1591,1,4.742303,creditcard,0.000000,0
39219,237,1,4.921318,creditcard,236.082639,0
39220,272,1,5.040929,paypal,0.000694,0

In [35]:
df = pd.get_dummies(dfp, columns=['paymentMethod'])

In [36]:
df

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,label,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
0,29,1,4.745402,28.204861,0,False,True,False
1,725,1,4.742303,0.000000,0,False,False,True
2,845,1,4.921318,0.000000,0,True,False,False
3,503,1,4.886641,0.000000,0,True,False,False
4,2000,1,5.040929,0.000000,0,True,False,False
...,...,...,...,...,...,...,...,...
39216,986,1,4.836982,0.000000,0,True,False,False
39217,1647,1,4.876771,377.930556,0,True,False,False
39218,1591,1,4.742303,0.000000,0,True,False,False
39219,237,1,4.921318,236.082639,0,True,False,False
39220,272,1,5.040929,0.000694,0,False,True,False

In [37]:
from sklearn.model_selection import train_test_split
#sklearn.model_selection: Tools for model selection, such as cross validation and hyper-parameter tuning.
#train_test_split: Split arrays or matrices into random train and test subsets.

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('label', axis=1), df['label'],
    test_size=0.33, random_state=17)

In [39]:
X_train
y_train

13272    0
22716    0
30255    0
7676     0
15105    0
        ..
31044    0
25631    0
33174    0
34959    0
10863    0
Name: label, Length: 26278, dtype: int64

In [40]:
from sklearn.linear_model import LogisticRegression
#sklearn.linear_model: A variety of linear models
#LogisticRegression: This model implements regularised logistic regression using a set of available solvers
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [41]:
y_pred = clf.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score
#sklearn.metrics: Score functions, performance metrics, pairwise metrics and distance computations.
#accuracy_score: In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.

In [43]:
print(accuracy_score(y_pred, y_test))

1.0

In [44]:
print(confusion_matrix(y_test, y_pred))

[[12753     0]
 [    0   190]]